### ISSUE TITLE
Failure to parse YAML

### ISSUE THREAD

**Issue by sherief** [biojppm/rapidyaml#3] opened 2018-02-27 06:43 UTC
I have some YAML code generated by yaml-cpp and according to yamllint.com, it is valid, but while yaml-cpp can parse it just fine rapidYAML seems to invoke the error handler when asked to parse it. A repro case is attached. 

[ryaml-repro.zip](https://github.com/biojppm/rapidyaml/files/1761511/ryaml-repro.zip)

**Comment by biojppm** [comment] 2018-02-27 16:07
Thanks for the report. Looking into it.

**Comment by biojppm** [comment] 2018-02-27 16:13
pasting the code in the zip for future reference:

```
#include <ryml.hpp>

#include <cstring>
#include <string>

using namespace std;

const char* const YAML =
R"str(

universe:
  objects:
    object:
      uuid: A7AB039C0EF3A74480A1B398247039A7
      components:
        - component:
            type: name component
            data:
              object name: Root Node
        - component:
            type: transform component
            data:
              translation: [-2, -2, 5]
              rotation: [0, 0, 0, 1]
              scaling: [1, 1, 1]
        - component:
            type: perspective camera component
            data:
              {}
        - component:
            type: mesh component
            data:
              mesh resource: TODO
        - component:
            type: lua script component
            data:
              {}
        - component:
            type: audio component
            data:
              audio resource: 
              type: 0
              current sample: 184102
              spatialized: true
      children:
        - object:
            uuid: E1C364A925D649408E83C8EEF5179A87
            components:
              - component:
                  type: name component
                  data:
                    object name: Prepend
            children:
              []
        - object:
            uuid: 377DBA885AF4CD42B8A56BB3471F60E5
            components:
              - component:
                  type: name component
                  data:
                    object name: pivot
            children:
              []
        - object:
            uuid: 6DD1835797DADB4F95232CE7E9DE41BA
            components:
              - component:
                  type: name component
                  data:
                    object name: Append
            children:
              []

)str";

int main()
{
    char* VarStr = (char*) malloc(strlen(YAML) + 1);
    memcpy(VarStr, YAML, strlen(YAML) + 1);
    auto tree = ryml::parse(
        c4::yml::span(
            VarStr, VarStr + (strlen(YAML))
            )
    );
    return 0;
}
```

**Comment by biojppm** [comment] 2018-02-27 18:16
Ok, so there at least are two problems here.

The first is simple: `translation: [-2, -2, 5]`. I was filtering out negative numbers. 

The second one is caused by this unquoted empty scalar: `audio resource: `. Shouldn't it have an empty quote? Anyway, ryml should handle this; currently its state machine is fooled by the absence of value. I'll fix this ASAP.

**Comment by biojppm** [comment] 2018-02-27 18:23
Turns out there's also another problem with the parser. The empty `{}` and `[]` on the next lines are breaking it too.

**Comment by biojppm** [comment] 2018-02-28 01:38
OK, the second problem (accepting null values) appears to be fixed. Rewiring the parser to accept null values took some work.

Now for the next one, the bracket pairs on the next line. I was going to say shouldn't take long, but I know better than to say it... :-)

**Comment by biojppm** [comment] 2018-02-28 02:28
Ok, that's it. All seems fixed now. ryml is still in its infancy and YAML is full of dark corners, so thanks for sticking.

**Comment by biojppm** [comment] 2018-02-28 03:02
By the way, let me suggest some simplifications to your code. Not that it's wrong -- actually getting there in such a poorly documented project clearly shows some skills.

First of all let me try to clarify the namespace confusion -- I get that I am not making it easier. I'm using this library in my own applications, where the c4 namespace is the top namespace, so I use c4::yml. Now, people using this as a standalone library should not have to use the c4::yml, so I just rename c4::yml as ryml (in ryml.hpp). So using ryml:: everywhere should just work (if it doesn't it's a bug).

Now about the YAML src copy for passing to ryml. Making it explicitly is burdensome, I see that. If you have a writable container, you can specialize `to_span()` for your type. This makes the code much more easy on the eye. Let me use std::string as an example here:

```c++
#include <string>
#include <ryml.hpp>
#include <ryml_std.hpp> // this header provides interoperation with std containers

int main()
{
    std::string src("foo: bar # yaml markup goes here");
    auto tree = ryml::parse(to_span(src)); // now ryml reads/writes into the string above
    return 0;
}
```

HTH.

**Closed by biojppm** 2018-02-28 03:02 UTC
Labels: bug

**Comment by sherief** [comment] 2018-02-28 03:43
I seriously was going to open an issue (or two) about the API and source organization, and was wondering whether it's better to wait till it matures a bit or not...

**Comment by biojppm** [comment] 2018-02-28 04:48
@sherief I've added above some more ways of bundling the buffer for calling ryml::parse(). Be sure to read. I'll put them also in the top level README for now.
