### ISSUE TITLE
Using of rapid yaml and std::filesystem simultaneously

### ISSUE THREAD

**Issue by vkorchagova** [biojppm/rapidyaml#99] opened 2020-12-21 11:13 UTC
Hello everyone!

I would like to create an application where both ryaml and std::filesystem are required. I build my app via cmake.
When I insert "ryml::ryml" string into the `target_link_libraries` list, I have an error "std::filesystem was not declared" despite the "-lstdc++fs". All is OK without "ryml::ryml" string in the `target_link_libraries` list.

Could anyone help me and explain, how to link both libraries correctly?

Part of my CMakeLists.txt:
```
find_package(ryml REQUIRED)
add_executable(${PROJECT_NAME} ${ALLFILES})
target_link_libraries(${PROJECT_NAME} PUBLIC -lstdc++fs ryml::ryml)
```
Also, I use c++17 in my app.

**Comment by vkorchagova** [comment] 2020-12-21 15:40
If I linked `libryml.a` like a static library, compilation without any ryml functions is OK. When I tried to run a tutorial from the repo, I saw the following compilation errors:
```
error:substr is not a member of ryml
     ryml::substr srcview = src_; // a mutable view to the source buffer
           ^~~~~~
/unicluster/home/viktoria.korchagova/RKDG/mfem/dgns/main.cpp:83:11: note: suggested alternative:
In file included from /unicluster/home/viktoria.korchagova/extendedSrc/rapidyaml-0.1.0/build/include/c4/yml/common.hpp:5,
                 from /unicluster/home/viktoria.korchagova/extendedSrc/rapidyaml-0.1.0/build/include/./c4/yml/./tree.hpp:7,
                 from /unicluster/home/viktoria.korchagova/extendedSrc/rapidyaml-0.1.0/build/include/./c4/yml/yml.hpp:4,
                 from /unicluster/home/viktoria.korchagova/extendedSrc/rapidyaml-0.1.0/build/include/ryml.hpp:4,
                 from /unicluster/home/viktoria.korchagova/RKDG/mfem/dgns/main.cpp:42:
/unicluster/home/viktoria.korchagova/extendedSrc/rapidyaml-0.1.0/build/include/c4/substr.hpp:31:51: note:   \u2018c4::substr\u2019
 using substr = C4CORE_EXPORT basic_substring<char>;
                                                   ^
/unicluster/home/viktoria.korchagova/RKDG/mfem/dgns/main.cpp:85:35: error: \u2018srcview\u2019 was not declared in this scope
     ryml::Tree tree = ryml::parse(srcview);
                                   ^~~~~~~
make[2]: *** [CMakeFiles/dgns.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/dgns.dir/all] Error 2
make: *** [all] Error 2
```
It seems very strange...

**Comment by vkorchagova** [comment] 2020-12-22 14:42
Success was reached after the following corrections:
1. `ryml::substr` -> `c4::substr`
2. `node["bar"][0]` -> `tree["bar"][0]`
3. `node["bar"][1]` -> `tree["bar"][1]`

 The whole code:
```
   // ryml can parse in situ (and read-only buffers too):
    char src[] = "{foo: 1, bar: [2, 3]}";
    c4::substr srcview = src; // a mutable view to the source buffer
    // there are also overloads for reusing the tree and parser
    ryml::Tree tree = ryml::parse(srcview);

    // get a reference to the "foo" node
    ryml::NodeRef node = tree["foo"];

    show_keyval(node);  // "foo: 1"
    show_val(tree["bar"][0]);  // "2"
    show_val(tree["bar"][1]);  // "3"
```

**Comment by biojppm** [comment] 2021-06-28 15:40
Hi @vkorchagova , thanks for reporting, and sorry for the really late reply. It seems you were having two separate problems. Since at the end you say you had success, 

  1. **problem with `std::filesystem`**. Was it a compiler or a linker error? Since filesystem is C++17, did you enable c++17 for both ryml and your app? What did you change that the fixed the problem for you?
  2.  **problem with namespace**. `ryml` is a rename of `c4::yml` and `substr` is available in both `c4::` (where it is declared) and `c4::yml::`. What headers did you include?

**Comment by biojppm** [comment] 2021-06-28 17:27
@vkorchagova I just checked; actually substr is not available in `ryml` namespace. I'll open a new issue to track that, this one should track the `filesystem` problem.

**Comment by biojppm** [comment] 2021-07-06 20:37
@vkorchagova I cannot reproduce the problem. Looking at your cmake code, you are manually linking libstdc++-fs. Which compiler is this? FWIW, if I do `set(CMAKE_CXX_STANDARD 17)` in the cmake file, it just works without any explicit linking.

**Comment by biojppm** [comment] 2021-07-08 09:10
Closing now; feel free to reopen if you reproduce the problem.

**Closed by biojppm** 2021-07-08 09:10 UTC
