### ISSUE TITLE
Scalars beginning with * are emitted as invalid yaml

### ISSUE THREAD

**Issue by Gei0r** [biojppm/rapidyaml#151] opened 2021-08-24 13:48 UTC
When setting a node value programmatically, it should be emitted with quotation if it starts with `*`, otherwise the emitted yaml is invalid.

Example:

```c++
#include <ryml.hpp>

int main()
{
    ryml::Tree tr;
    ryml::NodeRef root{tr.rootref()};
    root.set_type(ryml::MAP);

    ryml::NodeRef foo = root["foo"];
    foo = "*bar";

    ryml::emit(tr);   // foo: *bar     # INVALID, looks like a reference

    // explicitly set value to quoted - should happen automatically when value starts with *
    foo.set_type(foo.type() | ryml::VALQUO);

    ryml::emit(tr);   // foo: '*bar'   # OK
}
```

However, when *parsing* an unquoted value that starts with `*`, this should probably not be emitted with quotes, to preserve the reference when not calling `Tree::resolve()`.

**Comment by biojppm** [comment] 2021-08-24 15:32
It looks like the problem [is here](https://github.com/biojppm/rapidyaml/blob/ffed564a090546c2568e4813457bd71dcc2adb19/src/c4/yml/emit.def.hpp#L380):

```c++
    const bool needs_quotes = (
        was_quoted
        ||
        ((!s.is_number()) // is not a number
        &&
        (
            (s.len != s.trim(" \t\n\r").len) // has leading or trailing whitespace
            ||
            s.first_of("#:-?,\n{}[]'\"") != npos // has special chars
            ||
            (was_quoted && s[0] == '*')  // starts with * but is not a reference (empty string checked above)
            )
        ));
```
The second check to `was_quoted` likely should not be there. Offhand, I can't remember the context, so I can confirm later, but you can also quickly check it out.

**Comment by biojppm** [comment] 2021-08-24 15:34
And I think it should also check against `&` as well.

**Comment by Gei0r** [comment] 2021-08-25 07:05
That line [is from me](https://github.com/biojppm/rapidyaml/commit/a332fd6142e949fdf42cd05f87ca67c7d169d46d) 😉

The reason why I didn't add quoting for all scalars starting with `*` is this: When *not* using `Tree::resolve()`, parsing and re-emitting a yaml file with references will not produce the original output anymore (because the reference will then be quoted).

**Comment by biojppm** [comment] 2021-08-25 09:56
I am not very willing to add the `VALQUO` flag when setting the value, which if I understand correctly seems to be your proposed solution. That would require a scan of the scalar every time it is set, in a situation where the caller generally knows whether or not the flag is needed. (Though I acknowledge that there is a scan while emitting, which is the other side of the equation here).

I think the line we looked at above deserves further scrutiny. Specifically, the comment states that the scalar is _not_ a reference. How come? I think the answer is that it doesn't. The source of truth regarding whether it is or isn't a reference are the type flags, which should be checked upstream such that `_write_scalar()` is not called. Going up, and glancing at the `_do_visit()` function, there is no check to `.is_ref()` or similar. There are calls to `.is_anchor()`, but not to `.is_ref()`.

So I think the general solution is to add those checks in `.write_scalar()`, and remove the second check to `was_quoted` when emitting the scalar. Something like this for the scalar:

```c++
    const bool needs_quotes = (
        was_quoted
        ||
        ((!s.is_number()) // is not a number
        &&
        (
            (s.len != s.trim(" \t\n\r").len) // has leading or trailing whitespace
            ||
            s.first_of("#:-?,\n{}[]'\"") != npos // has special chars
            ||
            s.begins_with_any("*&") || s.begins_with("<<") // <----------------- here
            )
        ));
```

**Comment by biojppm** [comment] 2021-08-25 11:01
But you're right - there's also the problem you refer with parsing a reference, _not_ resolving and subsequently emitting, which must not use quotes. But there I think the solution is ensuring that upon parsing, the node must be marked as a `REF`. I will work a test to put all constraints in place.

**Comment by biojppm** [comment] 2021-08-25 11:15
Just a sketch for the test (the method names are very likely wrong, but IMO this should be the general intent):
```c++
Tree t = ryml::parse(R"(
foo: &foo 1
ref: *foo
quo: '*foo'
)");

EXPECT_TRUE(t["ref"].is_valref());
EXPECT_FALSE(t["quo"].is_valref());

EXPECT_FALSE(t["ref"].is_valquo());
EXPECT_TRUE(t["quo"].is_valquo());

t["prog_ref"].set_valref("*foo"); // need to explicitly set as VALREF
t["prog_quo"] = "*foo"; // no need to set VALQUO, emitting should add the quotes

EXPECT_EQ(ryml::emitrs<std::string>(t),
R"(foo: &foo 1
ref: *foo
quo: '*foo'
prog_ref: *foo
prog_quo: '*foo'
)");

t.resolve();

EXPECT_EQ(ryml::emitrs<std::string>(t),
R"(foo: 1
ref: 1
quo: '*foo'
prog_ref: 1
prog_quo: '*foo'
)");

```

**Comment by Gei0r** [comment] 2021-08-25 11:53
I agree that not calling `write_scalar()` for something that's not a scalar is more elegant.

And `is_val_ref()` already seems to work, even when *not* resoving:

```c++
#include <ryml.hpp>
#include <iostream>

int main()
{
    ryml::Tree tr = ryml::parse("{ a: *ref, b: '*not_a_ref' }");
    std::cout << tr["a"].is_val_ref() << "\n";   // --> true
    std::cout << tr["b"].is_val_ref() << "\n";   // --> false
}
```

**Closed** 2021-09-16 14:05 UTC
Labels: bug
