### ISSUE TITLE
overindented (likely valid) YAML causes abort

### ISSUE THREAD

**Issue by matt-deboer** [biojppm/rapidyaml#223] opened 2022-03-08 01:08 UTC
version: v0.4.0
compiler: clang-13
os: ubuntu 20.04

A bit of a strange case, but after checking a few yaml validators online, this yaml seems valid, but causes error:
```
auto yaml = R"config(
            A:
                - 1
                - 4
            B:
                - 2
                - 3
            )config";
ryml::Callbacks callbacks{};
callbacks.m_error = [](const char *msg, size_t msg_len, ryml::Location location, void *)
{
    throw std::runtime_error({msg, msg_len});
};
ryml::Tree tree{callbacks};
ryml::parse_in_arena(ryml::to_csubstr(yaml), &tree);
std::cout << "parsed:" << std::endl << tree << std::endl;
```
The output is:
```
_deps/ryml-src/ext/c4core/src/c4/substr.hpp:207: ERROR: check failed: i >= 0 && i < len

SIGABRT - Abort
```
(also fails to trigger the callbacks configured on `tree`)

yes, I'm aware that the yaml created by that multiline string literal is actually this (which yaml validators seem to think is fine):
```

            A:
                - 1
                - 4
            B:
                - 2
                - 3
            
```
checked at: 
- http://www.yamllint.com/
- https://codebeautify.org/yaml-validator

Is there something I'm using incorrectly? or is this a bug?

**Comment by biojppm** [comment] 2022-03-08 11:56
Thanks for reporting and for the MVE. That seems a bug indeed. However, the latest rapidyaml release correctly parses your input. Which version are you using?

(BTW, there is a very nice tool for comparing all the YAML parsers with live input (but it requires Docker), and there the result is green everywhere, including rapidyaml; [here's the encoded link if you want to try it](https://play.yaml.io/main/parser?input=CiAgICAgICAgICAgIEE6CiAgICAgICAgICAgICAgICAtIDEKICAgICAgICAgICAgICAgIC0gNAogICAgICAgICAgICBCOgogICAgICAgICAgICAgICAgLSAyCiAgICAgICAgICAgICAgICAtIDM=) )

**Comment by biojppm** [comment] 2022-03-08 13:38
I was looking again and while the link above does indeed parse successfully, adding a new indented line triggers the crash.
  * [passes](https://play.yaml.com/main/parser?input=CiAgICAgICAgICAgIEE6CiAgICAgICAgICAgICAgICAtIDEKICAgICAgICAgICAgICAgIC0gNAogICAgICAgICAgICBCOgogICAgICAgICAgICAgICAgLSAyCiAgICAgICAgICAgICAgICAtIDM=)
  * [fails](https://play.yaml.com/main/parser?input=CiAgICAgICAgICAgIEE6CiAgICAgICAgICAgICAgICAtIDEKICAgICAgICAgICAgICAgIC0gNAogICAgICAgICAgICBCOgogICAgICAgICAgICAgICAgLSAyCiAgICAgICAgICAgICAgICAtIDMKICAgICAgICAgICAgICAgIA==)
  * [passes](https://play.yaml.com/main/parser?input=CiAgICAgICAgICAgIEE6CiAgICAgICAgICAgICAgICAtIDEKICAgICAgICAgICAgICAgIC0gNAogICAgICAgICAgICBCOgogICAgICAgICAgICAgICAgLSAyCiAgICAgICAgICAgICAgICAtIDMKICAgICAgICAgICAgICAgICM=)
  * [fails](https://play.yaml.com/main/parser?input=CiAgICAgICAgICAgIEE6CiAgICAgICAgICAgICAgICAtIDEKICAgICAgICAgICAgICAgIC0gNAogICAgICAgICAgICBCOgogICAgICAgICAgICAgICAgLSAyCiAgICAgICAgICAgICAgICAtIDMKICAgICAgICAgICAg)
  * [fails](https://play.yaml.com/main/parser?input=CiAgICAgICAgICAgIEE6CiAgICAgICAgICAgICAgICAtIDEKICAgICAgICAgICAgICAgIC0gNAogICAgICAgICAgICBCOgogICAgICAgICAgICAgICAgLSAyCiAgICAgICAgICAgICAgICAtIDMKICAgICA=)
  * [passes](https://play.yaml.com/main/parser?input=CiAgICAgICAgICAgIEE6CiAgICAgICAgICAgICAgICAtIDEKICAgICAgICAgICAgICAgIC0gNAogICAgICAgICAgICBCOgogICAgICAgICAgICAgICAgLSAyCiAgICAgICAgICAgICAgICAtIDMK)
  * [passes](https://play.yaml.com/main/parser?input=CiAgICAgICAgICAgIEE6CiAgICAgICAgICAgICAgICAtIDEKICAgICAgICAgICAgICAgIC0gNAogICAgICAgICAgICAgICAgCiAgICAgICAgICAgIEI6CiAgICAgICAgICAgICAgICAtIDIKICAgICAgICAgICAgICAgIC0gMwo=)

Also, it looks like this is a problem parsing the final line, not necessarily caused by the indentation level:
  * [passes](https://play.yaml.com/main/parser?input=QToKICAtIDEKICAtIDQKQjoKICAtIDIKICAtIDMgICAgICAgICAgICAgIA==)
  * [fails](https://play.yaml.com/main/parser?input=QToKICAtIDEKICAtIDQKQjoKICAtIDIKICAtIDMKICA=)

**Comment by biojppm** [comment] 2022-03-09 01:24
@matt-deboer it was a silly thing, now fixed.

However, I pushed in haste and it went to master where it should have gone into a separate branch and go through a PR. I have reset master quickly to go back through the PR. Please wait while the CI does its thing.

**Closed** 2022-03-09 09:47 UTC
Labels: bug

**Comment by biojppm** [comment] 2022-03-09 15:03
@matt-deboer [release 0.4.1](https://github.com/biojppm/rapidyaml/releases/tag/v0.4.1) is out, fixing this.

**Comment by matt-deboer** [comment] 2022-03-09 18:32
Thanks for the quick response!
