### ISSUE TITLE
Question: Parsing Large YAML to JSON 

### ISSUE THREAD

**Issue by KaylaBCronk** [biojppm/rapidyaml#317] opened 2022-10-04 21:41 UTC
Multi-part question so please bear with me.

Here's my code: 
```c++
ryml::Tree tree = ryml::parse(c4::to_substr((test)));
auto json = ryml::emitrs_json<std::string>(tree);
```

Hoping to simply convert YAML to JSON using the rapidyaml library. 

I know that [this ](https://github.com/biojppm/rapidyaml/commit/ec6995d46ed310c1eb0b33084a6c286cd15ac00e) commit went into fix preserving quotes on scalar values, but when working with versions in YAML: `  version: 1.0.0` returns `"version": 1.0.0` which is not valid JSON. I'm sure I could come up with a workaround, but was unsure if you were aware of this potential problem. 

Lastly, when working with large YAML strings (7+ streams) quotations end up in random spots and end up making the returned json invalid. Example quotes around closing brackets: `   "}}}}}}}},"/v2":` as well as spacing with a description that doesn't end with a closing bracket will add a space and a new line then quotations making it invalid JSON: `{"description": "Authentication was successful. The session ID is returned in a cookie named `...`. You need to include this cookie in subsequent requests. If using a Web Browser it will handle the cookie for you. \n
",`

Maybe I'm converting to JSON improperly and there's an easy fix.

**Comment by biojppm** [comment] 2022-10-05 13:40
> I know that [this ](https://github.com/biojppm/rapidyaml/commit/ec6995d46ed310c1eb0b33084a6c286cd15ac00e) commit went into fix preserving quotes on scalar values, but when working with versions in YAML: `  version: 1.0.0` returns `"version": 1.0.0` which is not valid JSON. I'm sure I could come up with a workaround, but was unsure if you were aware of this potential problem. 

You are using an older version. The problem you describe has been recently fixed in #299.

Beware that some breaking changes were introduced in the meantime. See the current [changelog](https://github.com/biojppm/rapidyaml/tree/master/changelog/0.5.0.md) for details.

**Comment by biojppm** [comment] 2022-10-05 13:42
> Lastly, when working with large YAML strings (7+ streams) quotations end up in random spots and end up making the returned json invalid. Example quotes around closing brackets: "}}}}}}}},"/v2": as well as spacing with a description that doesn't end with a closing bracket will add a space and a new line then quotations making it invalid JSON: {"description": "Authentication was successful. The session ID is returned in a cookie named .... You need to include this cookie in subsequent requests. If using a Web Browser it will handle the cookie for you. \n ",

Sorry, this is too vague, and I can't understand your problem. Give me a MVE (Minimum Verifiable Example) which is valid C++ and reproduces your problem, and I'll be happy to help.

**Comment by KaylaBCronk** [comment] 2022-10-05 20:42
Forgive me if this is long, we're taking a YAML string (CStdString) and attempting to parse it into JSON using the rapadyaml library - here is the code below: 

```c++
int transformYaml(CStdString& str) {
	int length = str.size();
	std::string test = (const char*)(LPCTSTR)str;
	ryml::Tree tree = ryml::parse(c4::to_substr((test)));
	auto json = ryml::emitrs_json<std::string>(tree);
	strcpy((char*)str.GetBuffer(length), json.c_str());
	return json.size();
}
```

We're using this as a sample YAML string (we use the OpenAPI schema) 
```yaml
openapi: "3.0.0"
info:
  title: Simple API overview
  version: "2.0.0"
paths:
  /:
    get:
      operationId: listVersionsv2
      summary: List API versions
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              examples: 
                foo:
                  value:
                    {
                      "versions": [
                        {
                            "status": "CURRENT",
                            "updated": "2011-01-21T11:33:21Z",
                            "id": "v2.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v2/",
                                    "rel": "self"
                                }
                            ]
                        },
                        {
                            "status": "EXPERIMENTAL",
                            "updated": "2013-07-23T11:33:21Z",
                            "id": "v3.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v3/",
                                    "rel": "self"
                                }
                            ]
                        }
                      ]
                    }
        '300':
          description: |-
            300 response
          content:
            application/json: 
              examples: 
                foo:
                  value: |
                   {
                    "versions": [
                          {
                            "status": "CURRENT",
                            "updated": "2011-01-21T11:33:21Z",
                            "id": "v2.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v2/",
                                    "rel": "self"
                                }
                            ]
                        },
                        {
                            "status": "EXPERIMENTAL",
                            "updated": "2013-07-23T11:33:21Z",
                            "id": "v3.0",
                            "links": [
                                {
                                    "href": "http://127.0.0.1:8774/v3/",
                                    "rel": "self"
                                }
                            ]
                        }
                    ]
                   }
 ```
 
 When running it through the json emitr it returns: 
 ```json
{"openapi": "3.0.0","info": {"title": "Simple API overview","version": "2.0.0"},"paths": {"/": {"get": {"operationId": "listVersionsv2","summary": "List API versions","responses": {"200": {"description": "200 response","content": {"application/json": {"examples": {"foo": {"value": {"versions": [{"status": "CURRENT","updated": "2011-01-21T11:33:21Z","id": "v2.0","links": [{"href": "http://127.0.0.1:8774/v2/","rel": "self"}]},{"status": "EXPERIMENTAL","updated": "2013-07-23T11:33:21Z","id": "v3.0","links": [{"href": "http://127.0.0.1:8774/v3/","rel": "self"}]}]}}}}}},"300": {"description": "300 response","content": {"application/json": {"examples": {"foo": {"value": "{
 "versions": [
       {
         "status": "CURRENT",
         "updated": "2011-01-21T11:33:21Z",
         "id": "v2.0",
         "links": [
             {
                 "href": "http://127.0.0.1:8774/v2/",
                 "rel": "self"
             }
         ]
     },
     {
         "status": "EXPERIMENTAL",
         "updated": "2013-07-23T11:33:21Z",
         "id": "v3.0",
         "links": [
             {
                 "href": "http://127.0.0.1:8774/v3/",
                 "rel": "self"
             }
         ]
     }
 ]
}
"}}}}}}}}}}
```
 As you can see it's putting quotations around brackets where they aren't needed. Like I said previously perhaps I'm doing something wrong. 
 
 Unfortunately our project doesn't use cmake so we're unable to build the latest on the fly - we use vcpkg as our package manager and import the lib files and includes as needed. Do you update vcpkg regularly?

**Comment by biojppm** [comment] 2022-10-05 22:06
Your code, with my comments:
```c++
int transformYaml(CStdString& str) {
  int length = str.size();
  std::string test = (const char*)(LPCTSTR)str;
  // ok, this is parsing in place
  ryml::Tree tree = ryml::parse(c4::to_substr((test)));
  // ok, this will get you a JSON buffer
  auto json = ryml::emitrs_json<std::string>(tree);
  // BAD, undefined behavior: how do you know that 
  // length is larger than json.size()?
  strcpy((char*)str.GetBuffer(length), json.c_str());
  return json.size();
}
```
There's nothing wrong with the calls to ryml code, except for maybe an extra copy which is not needed.

But there is something really wrong with what you're doing afterwards. You are assuming that the length of the JSON output string is smaller than `length`, but you cannot be sure. At the very least, you need to protect that with an `if((size_t)length > json.size())`, and then maybe use `strncpy()` with a safe destination buffer length (but ensuring the `\0` gets added).

On top of this, I'm not sure what the `strcpy()` is going to do with the terminating `\0`. From the output it seems that the buffer in `str.GetBuffer(length)` is not zero terminated, which would explain the garbage `"}}}}}}}}}}` at the end.

> Unfortunately our project doesn't use cmake so we're unable to build the latest on the fly - we use vcpkg as our package manager and import the lib files and includes as needed. Do you update vcpkg regularly?

I don't update vcpkg at all. It is maintained downstream by other people who need it. If you need it now, you can send a Pull Request to vcpkg (but you will need to wait for an official release from here, which is pending). Or you can pick one of the alternative ways to consume ryml that are described in the README. Eg, use ryml as a git submodule of your project, or just pick the aggregated single-header from the artifacts of a successful CI run, or build the header yourself.

**Comment by KaylaBCronk** [comment] 2022-10-05 22:28
**Thank you** for your thorough explanation, I've spent 4 years working in backend Java code that c++ is completely new to me. Not sure if you scrolled all the way over in the JSON file, but there's more quotation marks that get randomly added besides the ending errors. 

I actually grabbed the `json` string from the debugger before it gets put through the `strcpy()` so I don't think the errors are coming from that call. (I've been wrong before though.) 


Also thank you for clarifying where the single-header comes from, I was lost when reading the readme.

**Comment by biojppm** [comment] 2022-10-05 22:58
OK.

I quadruple-checked, and am really sure that rapidyaml is not adding or removing anything from this tree:
```c++
    const Tree t0 = parse_in_arena(yaml);
    std::string json0 = emitrs_json<std::string>(t0);
    const Tree t1 = parse_in_arena(to_csubstr(json0));
    std::string json1 = emitrs_json<std::string>(t0);
    assert(json1 == json0);
    const Tree t2 = parse_in_arena(to_csubstr(json1));
    std::string json2 = emitrs_json<std::string>(t2);
    assert(json2 == json0);
    const Tree t3 = parse_in_arena(to_csubstr(json2));
    std::string json3 = emitrs_json<std::string>(t3);
    assert(json3 == json0);
```
The code above parses your YAML block and emits it, then parses and so on. And the emitted strings are all the same.

But while checking I noticed the following. You have something odd in your YAML which may explain the situation. Consider this bit for the `200` response:
```yaml
        '200':
          description: |-
            200 response
          content:
            application/json:
              examples: 
                foo:
                  value:
                    {
                      "versions": [
```
... and now compare with the `300` response:
```yaml
        '300':
          description: |-
            300 response
          content:
            application/json: 
              examples: 
                foo:
                  value: |            # <<<<< THIS. Should this be here?
                   {
                    "versions": [
                          {
```
The `|` will make the whole value dictionary a plain string. I don't think that's intended, specially since this is from a schema.

And to be clear, the test code I pasted above succeeds both with and without the `|`.

**Comment by biojppm** [comment] 2022-10-05 23:01
And FWIW, this is the JSON string I get (without `|`):
```json
{"openapi": "3.0.0","info": {"title": "Simple API overview","version": "2.0.0"},"paths": {"/": {"get": {"operationId": "listVersionsv2","summary": "List API versions","responses": {"200": {"description": "200 response","content": {"application/json": {"examples": {"foo": {"value": {"versions": [{"status": "CURRENT","updated": "2011-01-21T11:33:21Z","id": "v2.0","links": [{"href": "http://127.0.0.1:8774/v2/","rel": "self"}]},{"status": "EXPERIMENTAL","updated": "2013-07-23T11:33:21Z","id": "v3.0","links": [{"href": "http://127.0.0.1:8774/v3/","rel": "self"}]}]}}}}}},"300": {"description": "300 response","content": {"application/json": {"examples": {"foo": {"value": {"versions": [{"status": "CURRENT","updated": "2011-01-21T11:33:21Z","id": "v2.0","links": [{"href": "http://127.0.0.1:8774/v2/","rel": "self"}]},{"status": "EXPERIMENTAL","updated": "2013-07-23T11:33:21Z","id": "v3.0","links": [{"href": "http://127.0.0.1:8774/v3/","rel": "self"}]}]}}}}}}}}}}}
```
There are a lot of `}` at the end, but that's because of the schema.

**Comment by biojppm** [comment] 2022-10-05 23:42
And a final note to suggest to emit directly into the buffer, doing away with the `strcpy()` chicanery. First, consider this overload of `ryml::emitrs_json()` in `ryml/emit.hpp`:
```c++
/** emit+resize: emit JSON to the given std::string/std::vector-like
 * container, resizing it as needed to fit the emitted JSON. */
template<class CharOwningContainer>
substr emitrs_json(Tree const& t, size_t id, CharOwningContainer * cont)
{
    substr buf = to_substr(*cont);
    substr ret = emit_json(t, id, buf, /*error_on_excess*/false);
    if(ret.str == nullptr && ret.len > 0)
    {
        cont->resize(ret.len);
        buf = to_substr(*cont);
        ret = emit_json(t, id, buf, /*error_on_excess*/true);
    }
    return ret;
}
```
if `CStdString` has `.resize()`, you can use the `emitrs_json()` with `CStdString` by simply define this function in the same namespace as `CStdString` and ryml should pick it up in `emitrs_json()`:
```c++
ryml::substr to_substr(CStdString& str){
   // just an illustration - not sure if this is right
   return {(char*)str.GetBuffer(), str.size()};
}
```
... and now you can just do this:
```c++
int transformYaml(CStdString& str) {
  int length = str.size();
  std::string test = (const char*)(LPCTSTR)str; // not sure if the cast is ok.
  ryml::Tree tree = ryml::parse(ryml::to_substr(test));
  // emit directly to the buffer
  ryml::substr result = emitrs_json(tree, &str);
  // if we are here then the output buffer can accomodate the JSON code.
  // (otherwise, it would call the error callback, and never get here)
  // Now, add the terminating \0
  if(result.size() + 1 <= buffer.size()) {
    buffer[result.size()] == '\0';
  }
  else {
     // FAIL: buffer not large enough for \0
     ....
  }
  return result.size() + 1;
}
```
If `CStdString` does not have `.resize()`, you can copy `ryml::emitrs_json()` and specialize it:
```c++
substr emitrs_json(Tree const& t, size_t id, CStdString * cont)
{
    substr buf = to_substr(*cont); // ... or equivalent
    substr ret = emit_json(t, id, buf, /*error_on_excess*/false);
    if(ret.str == nullptr && ret.len > 0)
    {
        cont->ResizeThis(ret.len); // ... or equivalent
        buf = to_substr(*cont); // ... or equivalent
        ret = emit_json(t, id, buf, /*error_on_excess*/true);
    }
    return ret;
}
``` 
All of this may seem large, but is simpler than it looks.

**Comment by KaylaBCronk** [comment] 2022-10-06 15:30
Wow, forgive me for the slow reply as this is a lot to take in. Thank you for the thorough reply, I can't put into words how much I appreciate it. 

I think maybe my main problem is having an older version, so using the single header file sounds helpful. I've poked around in actions tab and haven't had any luck locating the ryml_all.hpp file. (Last silly question I'll ask you for a while) Where can I grab that? I've downloaded the dist.zip from a successful run and don't believe I saw it in there.

**Comment by biojppm** [comment] 2022-10-06 21:32
You were close. The header is an artifact of the [release action](https://github.com/biojppm/rapidyaml/actions/workflows/release.yml), archived under `assets.zip`.

![image](https://user-images.githubusercontent.com/325344/194422264-f2da1d38-ce5a-4c41-ae56-d1b0f47fe702.png)

**Comment by biojppm** [comment] 2022-10-06 21:35
But note that getting the recent version will only fix the missing quotes from `version: "2.0.0"`. 

There is still the `|` question in the `300` callback, as I conveyed above.

**Comment by KaylaBCronk** [comment] 2022-10-06 22:10
Okay, **this** is my last question (promise) - I have the asset.zip downloaded and am looking through it (have been for the past few minutes) and can't find the ryml_all.hpp. Do you happen to know the directory in which it's located? (So sorry, I usually don't need to have someone hold my hand to walk me through these things.) 

As for your second comment - the sample schema I posted earlier was taken from the internet as a test, I have used some internal schemas we have since and ryml works flawlessly.

**Comment by biojppm** [comment] 2022-10-07 00:11
IIRC the header is suffixed with the commit, (or the git tag when it is a release). There is only one hpp header there, so just rename it to whatever you like.

**Closed** 2022-10-07 13:52 UTC
