### ISSUE TITLE
Parser doesn't accept space before colon

### ISSUE THREAD

**Issue by Gei0r** [biojppm/rapidyaml#65] opened 2020-05-15 11:17 UTC
The ryml parser does not accept a space before the colon if the parent object is enclosed in braces.

```c++
#include <ryml.hpp>

int main()
{
    ryml::Tree t = ryml::parse("{a : b}");

    // This works:
    // ryml::Tree t = ryml::parse("a : b");
}
```
Output:
```
1:3: (2B):ERROR: ERROR parsing yml: parse error
line 1: '{a : b}' (sz=7)
           ^~~~~  (cols 3-8)
```

**Comment by biojppm** [comment] 2020-05-15 12:11
Thanks again for the repro; again, allow me some days to fix this.

**Comment by biojppm** [comment] 2020-05-15 16:31
This is a duplicate of #54 ; moving work there.

**Closed by biojppm** 2020-05-15 16:31 UTC
Labels: bug
