### ISSUE TITLE
Release plans?

### ISSUE THREAD

**Issue by williamfgc** [biojppm/rapidyaml#18] opened 2019-11-04 15:07 UTC
Thanks for the interesting work done on rapidyaml. We are looking at available options for C++ yaml readers. Are there any plans for an upcoming release, even if it's not stable (e.g. 0.1) ? Thanks.

**Comment by biojppm** [comment] 2020-01-20 21:05
Hi @williamfgc,

Thanks for the interest. I have no release approach yet, as I am working first on installs and plan to work later on YAML test conformance.

However, note that all development is made in the dev branch, and every subsequent merge to the master branch is done only if the CI tests succeed. So you can expect the master branch to be stable; certainly you can expect no regressions to appear there.

**Comment by saraedum** [comment] 2020-10-17 18:52
Is there any news on this @biojppm? I was thinking about packaging rapidyaml for conda-forge but it would be much easier if there were a version number attached to some state of the master branch.

**Comment by saraedum** [comment] 2020-10-18 14:58
I made a first attempt to package this for conda-forge here https://github.com/conda-forge/staged-recipes/pull/12928

(It fails on macOS due to #75 and on Windows because there is no release tarball yet.)

**Comment by biojppm** [comment] 2020-10-19 12:28
@saraedum Thanks. I will now look at versioning and then packaging. Hopefully to be ready by next week.

**Comment by biojppm** [comment] 2020-11-03 01:28
Finally [the first release is out, at 0.1.0](https://github.com/biojppm/rapidyaml/releases/tag/v0.1.0). I'm closing this, but feel free to reopen if anything's not right.

**Closed by biojppm** 2020-11-03 01:28 UTC
