### ISSUE TITLE
Compilation error "no matching function for call to 'from_chars'" for size_t

### ISSUE THREAD

**Issue by cvet** [biojppm/rapidyaml#11] opened 2019-09-15 10:38 UTC
Hi! Here is compilation issue in function
size_t Tree::_next_node(lookup_result * r, bool modify, _lookup_path_token *parent)
<details><summary>Full log</summary><pre><code>
[  0%] Building CXX object ThirdParty/rapidyaml/CMakeFiles/ryml.dir/src/c4/yml/tree.cpp.o
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/src/c4/yml/tree.cpp:1430:15: error: no matching function for call to 'from_chars'
        if( ! from_chars(tk, &idx))
              ^~~~~~~~~~
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:732:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'void **__restrict' for 2nd argument
_C4_DEFINE_TO_FROM_CHARS(void*   , "p"             , "p"             )
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:715:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS'
inline bool from_chars(csubstr buf, ty * C4_RESTRICT v)                 \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:733:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'float *__restrict' for 2nd argument
_C4_DEFINE_TO_FROM_CHARS_TOA(   float, f)
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:627:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS_TOA'
inline bool from_chars(csubstr buf, ty *C4_RESTRICT v)          \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:734:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'double *__restrict' for 2nd argument
_C4_DEFINE_TO_FROM_CHARS_TOA(  double, d)
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:627:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS_TOA'
inline bool from_chars(csubstr buf, ty *C4_RESTRICT v)          \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:735:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'int8_t *__restrict' (aka 'signed char *__restrict') for 2nd argument
_C4_DEFINE_TO_FROM_CHARS_TOA(  int8_t, i)
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:627:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS_TOA'
inline bool from_chars(csubstr buf, ty *C4_RESTRICT v)          \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:736:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'int16_t *__restrict' (aka 'short *__restrict') for 2nd argument
_C4_DEFINE_TO_FROM_CHARS_TOA( int16_t, i)
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:627:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS_TOA'
inline bool from_chars(csubstr buf, ty *C4_RESTRICT v)          \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:737:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'int32_t *__restrict' (aka 'int *__restrict') for 2nd argument
_C4_DEFINE_TO_FROM_CHARS_TOA( int32_t, i)
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:627:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS_TOA'
inline bool from_chars(csubstr buf, ty *C4_RESTRICT v)          \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:738:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'int64_t *__restrict' (aka 'long long *__restrict') for 2nd argument
_C4_DEFINE_TO_FROM_CHARS_TOA( int64_t, i)
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:627:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS_TOA'
inline bool from_chars(csubstr buf, ty *C4_RESTRICT v)          \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:739:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'uint8_t *__restrict' (aka 'unsigned char *__restrict') for 2nd argument
_C4_DEFINE_TO_FROM_CHARS_TOA( uint8_t, u)
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:627:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS_TOA'
inline bool from_chars(csubstr buf, ty *C4_RESTRICT v)          \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:740:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'uint16_t *__restrict' (aka 'unsigned short *__restrict') for 2nd argument
_C4_DEFINE_TO_FROM_CHARS_TOA(uint16_t, u)
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:627:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS_TOA'
inline bool from_chars(csubstr buf, ty *C4_RESTRICT v)          \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:741:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'uint32_t *__restrict' (aka 'unsigned int *__restrict') for 2nd argument
_C4_DEFINE_TO_FROM_CHARS_TOA(uint32_t, u)
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:627:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS_TOA'
inline bool from_chars(csubstr buf, ty *C4_RESTRICT v)          \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:742:1: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'uint64_t *__restrict' (aka 'unsigned long long *__restrict') for 2nd argument
_C4_DEFINE_TO_FROM_CHARS_TOA(uint64_t, u)
^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:627:13: note: expanded from macro '_C4_DEFINE_TO_FROM_CHARS_TOA'
inline bool from_chars(csubstr buf, ty *C4_RESTRICT v)          \
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:773:13: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'bool *__restrict' for 2nd argument
inline bool from_chars(csubstr buf, bool * C4_RESTRICT v)
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:804:13: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'char *__restrict' for 2nd argument
inline bool from_chars(csubstr buf, char * C4_RESTRICT v)
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:833:13: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'c4::csubstr *__restrict' (aka 'basic_substring<const char> *__restrict') for 2nd argument
inline bool from_chars(csubstr buf, csubstr *C4_RESTRICT v)
            ^
/jenkins/workspace/fonline_dev/ThirdParty/rapidyaml/extern/c4core/src/c4/to_chars.hpp:862:13: note: candidate function not viable: no known conversion from 'size_t *' (aka 'unsigned long *') to 'c4::substr *__restrict' (aka 'basic_substring<char> *__restrict') for 2nd argument
inline bool from_chars(csubstr buf, substr * C4_RESTRICT v)
            ^
1 error generated.
make[3]: *** [ThirdParty/rapidyaml/CMakeFiles/ryml.dir/src/c4/yml/tree.cpp.o] Error 1
</code></pre></details>

**Comment by biojppm** [comment] 2019-10-19 15:37
Hi @cvet, thanks for reporting this. I've been very busy in the last weeks and somehow missed your report. For now, I can only make this quick note to let you know I'll investigate ASAP.

**Comment by cvet** [comment] 2019-10-21 10:33
Hi! No, I am already made workaround for me, this is only for you known. Thanks!

**Comment by biojppm** [comment] 2019-10-21 13:29
Well, was it something from ryml which forced you to workaround on? To be clear, `from_chars()` has overloads for all the intrinsic types, so seeing this error is strange. Or was it something from your side?

**Comment by biojppm** [comment] 2020-01-20 20:44
Cannot reproduce, closing.

**Closed by biojppm** 2020-01-20 20:44 UTC
