### ISSUE TITLE
The rapidyaml package from PyPi requires libpython3.9.so regardless of the Python version used

### ISSUE THREAD

**Issue by mkurc-ant** [biojppm/rapidyaml#146] opened 2021-07-30 08:54 UTC
It looks like the package published to PyPi (`rapidyaml-0.1.0.post60`) always tries to link `libpython3.9.so.1.0` when imported even when installed and used by Python 3.7 or 3.8. This silently succeeds (and the package works afterwards) when one has Python 3.9 libraries installed in the system.

To reproduce try installing it in a virutalenv set up for Python 3.7 / 3.8 (on Linux):
```
virtualenv -p python3.7 env
source env/bin/activate
pip install rapidyaml
python -c "import ryml"
```

The last command should fail with something like:
```
Traceback (most recent call last):
  File "/home/mkurc/Work/env7/lib/python3.7/site-packages/ryml/ryml.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/mkurc/Work/env7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```

In case it succeeds (because there is `libpython3.9.so.1.0` somewhere in the system) one may try:
```
strace python -c "import ryml" 2>&1 | grep libpython3
```
This should list all `libpython3.*` shared objects that the Python interpreter tries to link. All of them refer to different locations of `libpython3.9.so.1.0`.

I've noticed that the CI build system that presumably builds the package fir PyPi does not enforce Python version anywhere. I'm not an expert on Swig but shouldn't the package be built separately for each supported Python 3.x version ?

**Comment by biojppm** [comment] 2021-07-30 16:23
Thanks for reporting.

@mithro or  @litghost - as the owners of the python package, do any of you guys want to pick this up?

The quickest way to address this would be to upload manually built packages for the different python versions. But in the future, we could set up a github workflow action to publish the python packages when making the release. What do you say?

**Comment by mithro** [comment] 2021-07-30 16:34
@biojppm - We should most certainly set up a GitHub workflow to publish the Python packages.

**Comment by mithro** [comment] 2021-07-30 16:36
Looking at https://pypi.org/manage/project/rapidyaml/release/0.1.0.post60/ it seems like only a source package is uploaded, so I'm unclear how this is ending up linked against `libpython3.9.so.1.0`?

**Comment by mithro** [comment] 2021-07-30 16:37
BTW @biojppm - I would be more than happy to add you as an owner of the PyPi package too.

**Comment by biojppm** [comment] 2021-09-18 12:39
@mkurc-ant I am working on getting compiled packages into the PyPI repo. But that is unrelated to the actual problem you describe, since you are using a source package.

And to be clear I am unable to reproduce the problem. For example:
```console
# create a pristine 3.8 environment 
vagrant@ubuntu1804:~$ PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.8.4
Downloading Python-3.8.4.tar.xz...
-> https://www.python.org/ftp/python/3.8.4/Python-3.8.4.tar.xz
Installing Python-3.8.4...
Installed Python-3.8.4 to /home/vagrant/.pyenv/versions/3.8.4

# activate it
vagrant@ubuntu1804:~$ pyenv local 3.8.4

# install rapidyaml from PyPI
vagrant@ubuntu1804:~$ pip install rapidyaml
Processing ./.cache/pip/wheels/aa/50/61/c90c447e069ac57b80e025b7f5583f42369244393062ce2268/rapidyaml-0.1.0.post60-cp38-cp38-linux_x86_64.whl
Installing collected packages: rapidyaml
Successfully installed rapidyaml-0.1.0.post60
WARNING: You are using pip version 20.1.1; however, version 21.2.4 is available.
You should consider upgrading via the '/home/vagrant/.pyenv/versions/3.8.4/bin/python3.8 -m pip install --upgrade pip' command.
vagrant@ubuntu1804:~$ python -c "import ryml" && echo SUCCESS
SUCCESS
```
The same thing happens if I use python 3.7.

This also goes to support the observation by @mithro above that the current rapidyaml in PyPI is a source package. Maybe the problems you are seeing are caused by something in your build environment?

**Comment by biojppm** [comment] 2021-09-18 13:09
Here's the log of a fresh rapidyaml (skipping the dependencies):
```
  Running command /home/vagrant/.pyenv/versions/3.8.4/bin/python3.8 /home/vagrant/.pyenv/versions/3.8.4/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplbsayph2
  Getting requirements to build wheel ... done
    Created temporary directory: /tmp/pip-modern-metadata-zcidjnoq
    Running command /home/vagrant/.pyenv/versions/3.8.4/bin/python3.8 /home/vagrant/.pyenv/versions/3.8.4/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpdxsiq_t1
    running dist_info
    creating /tmp/pip-modern-metadata-zcidjnoq/rapidyaml.egg-info
    writing /tmp/pip-modern-metadata-zcidjnoq/rapidyaml.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-modern-metadata-zcidjnoq/rapidyaml.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-modern-metadata-zcidjnoq/rapidyaml.egg-info/top_level.txt
    writing manifest file '/tmp/pip-modern-metadata-zcidjnoq/rapidyaml.egg-info/SOURCES.txt'
    listing git files failed - pretending there aren't any
    reading manifest file '/tmp/pip-modern-metadata-zcidjnoq/rapidyaml.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE.txt'
    writing manifest file '/tmp/pip-modern-metadata-zcidjnoq/rapidyaml.egg-info/SOURCES.txt'
    creating '/tmp/pip-modern-metadata-zcidjnoq/rapidyaml.dist-info'
    adding license file "LICENSE.txt" (matched pattern "LICEN[CS]E*")
    Preparing wheel metadata ... done
  Source in /tmp/pip-install-itn4kps3/rapidyaml has version 0.1.0.post60, which satisfies requirement rapidyaml from https://files.pythonhosted.org/packages/55/a5/66e07773163aa004812f00e9f3529531f9d5715fe290ce4b085f6e7856c0/rapidyaml-0.1.0.post60.tar.gz#sha256=9b76395ac495e8b03966149533305db29a60e38f487f18658d5976cb84239803
  Removed rapidyaml from https://files.pythonhosted.org/packages/55/a5/66e07773163aa004812f00e9f3529531f9d5715fe290ce4b085f6e7856c0/rapidyaml-0.1.0.post60.tar.gz#sha256=9b76395ac495e8b03966149533305db29a60e38f487f18658d5976cb84239803 from build tracker '/tmp/pip-req-tracker-5x5159tw'
Building wheels for collected packages: rapidyaml
  Created temporary directory: /tmp/pip-wheel-g5z9ego2
  Destination directory: /tmp/pip-wheel-g5z9ego2
  Running command /home/vagrant/.pyenv/versions/3.8.4/bin/python3.8 /home/vagrant/.pyenv/versions/3.8.4/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp3w4jmhuu
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/ryml
  copying api/python/ryml/__init__.py -> build/lib.linux-x86_64-3.8/ryml
  copying api/python/ryml/version.py -> build/lib.linux-x86_64-3.8/ryml
  running egg_info
  writing api/python/rapidyaml.egg-info/PKG-INFO
  writing dependency_links to api/python/rapidyaml.egg-info/dependency_links.txt
  writing top-level names to api/python/rapidyaml.egg-info/top_level.txt
  listing git files failed - pretending there aren't any
  reading manifest file 'api/python/rapidyaml.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE.txt'
  writing manifest file 'api/python/rapidyaml.egg-info/SOURCES.txt'
  creating build/lib.linux-x86_64-3.8/ryml/tests
  copying api/python/ryml/tests/parse.py -> build/lib.linux-x86_64-3.8/ryml/tests
  copying api/python/ryml/tests/parse_bm.py -> build/lib.linux-x86_64-3.8/ryml/tests
  running build_ext
  -- The CXX compiler identification is GNU 7.5.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- ryml: using C++ standard: C++11
  -- ryml: setting C++ standard: 11
  -- ryml: setting C++ standard required: ON
  -- ryml: importing subproject c4core (SUBDIRECTORY)... /tmp/pip-install-itn4kps3/rapidyaml/ext/c4core
  -- c4core: using C++ standard: C++11
  -- ryml: -----> target ryml PUBLIC incorporating lib c4core
  -- ryml: packing the project
  -- ryml: enabling API
  -- Found SWIG: /usr/bin/swig3.0 (found version "3.0.12")
  -- ryml: found swig 3.0.12: /usr/bin/swig3.0
  -- ryml: enabling python3 API
  -- Found Python3: /home/vagrant/.pyenv/versions/3.8.4/bin/python3.8 (found version "3.8.4") found components: Interpreter Development Development.Module Development.Embed
  -- ryml: found python 3.8.4: /home/vagrant/.pyenv/versions/3.8.4/bin/python3.8
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-itn4kps3/rapidyaml/build/temp.linux-x86_64-3.8_ryml.ryml
  [1/37] Building CXX object CMakeFiles/ryml.dir/src/c4/yml/common.cpp.o
  [2/37] Building CXX object CMakeFiles/ryml.dir/src/c4/yml/preprocess.cpp.o
  [3/37] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/error.cpp.o
  [4/37] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/base64.cpp.o
  [5/37] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/char_traits.cpp.o
  [6/37] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/time.cpp.o
  [7/37] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/format.cpp.o
  [8/37] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/language.cpp.o
  [9/37] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/memory_resource.cpp.o
  [10/37] Building CXX object CMakeFiles/ryml.dir/src/c4/yml/tree.cpp.o
  [11/37] Building CXX object CMakeFiles/ryml.dir/ext/c4core/src/c4/memory_util.cpp.o
  [12/37] Building CXX object CMakeFiles/ryml.dir/src/c4/yml/parse.cpp.o
  [13/37] Building CXX object subprojects/c4core/build/CMakeFiles/c4core.dir/src/c4/error.cpp.o
  [14/37] Linking CXX static library libryml.a
  [15/37] Building CXX object subprojects/c4core/build/CMakeFiles/c4core.dir/src/c4/char_traits.cpp.o
  [16/37] Building CXX object subprojects/c4core/build/CMakeFiles/c4core.dir/src/c4/base64.cpp.o
  [17/37] Building CXX object subprojects/c4core/build/CMakeFiles/c4core.dir/src/c4/time.cpp.o
  [18/37] Building CXX object subprojects/c4core/build/CMakeFiles/c4core.dir/src/c4/language.cpp.o
  [19/37] Building CXX object subprojects/c4core/build/CMakeFiles/c4core.dir/src/c4/memory_util.cpp.o
  [20/37] Building CXX object subprojects/c4core/build/CMakeFiles/c4core.dir/src/c4/format.cpp.o
  [21/37] Building CXX object subprojects/c4core/build/CMakeFiles/c4core.dir/src/c4/memory_resource.cpp.o
  [22/37] Linking CXX static library subprojects/c4core/build/libc4core.a
  [23/37] Swig compile /tmp/pip-install-itn4kps3/rapidyaml/api/ryml.i for python
  [24/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/src/c4/yml/common.cpp.o
  [25/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/src/c4/yml/tree.cpp.o
  [26/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/src/c4/yml/parse.cpp.o
  [27/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/ext/c4core/src/c4/error.cpp.o
  [28/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/src/c4/yml/preprocess.cpp.o
  [29/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/ext/c4core/src/c4/base64.cpp.o
  [30/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/ext/c4core/src/c4/char_traits.cpp.o
  [31/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/ext/c4core/src/c4/time.cpp.o
  [32/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/ext/c4core/src/c4/language.cpp.o
  [33/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/ext/c4core/src/c4/format.cpp.o
  [34/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/ext/c4core/src/c4/memory_resource.cpp.o
  [35/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/__/ext/c4core/src/c4/memory_util.cpp.o
  [36/37] Building CXX object api/CMakeFiles/ryml-api-python3.dir/src/python3/rymlPYTHON_wrap.cxx.o
  [37/37] Linking CXX shared module api/python3/_ryml.so
  -- Install configuration: "Release"
  -- Installing: /tmp/pip-install-itn4kps3/rapidyaml/build/lib.linux-x86_64-3.8/ryml/_ryml.so
  -- Set runtime path of "/tmp/pip-install-itn4kps3/rapidyaml/build/lib.linux-x86_64-3.8/ryml/_ryml.so" to ""
  -- Installing: /tmp/pip-install-itn4kps3/rapidyaml/build/lib.linux-x86_64-3.8/ryml/ryml.py

  ==> Configuring:
  $ cmake -S /tmp/pip-install-itn4kps3/rapidyaml -B /tmp/pip-install-itn4kps3/rapidyaml/build/temp.linux-x86_64-3.8_ryml.ryml -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-itn4kps3/rapidyaml/build/lib.linux-x86_64-3.8/ryml -DRYML_BUILD_API:BOOL=ON

  ==> Building:
  $ cmake --build /tmp/pip-install-itn4kps3/rapidyaml/build/temp.linux-x86_64-3.8_ryml.ryml --config Release

  ==> Installing:
  $ cmake --install /tmp/pip-install-itn4kps3/rapidyaml/build/temp.linux-x86_64-3.8_ryml.ryml --component python

  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/ryml
  copying build/lib.linux-x86_64-3.8/ryml/_ryml.so -> build/bdist.linux-x86_64/wheel/ryml
  copying build/lib.linux-x86_64-3.8/ryml/__init__.py -> build/bdist.linux-x86_64/wheel/ryml
  creating build/bdist.linux-x86_64/wheel/ryml/tests
  copying build/lib.linux-x86_64-3.8/ryml/tests/parse.py -> build/bdist.linux-x86_64/wheel/ryml/tests
  copying build/lib.linux-x86_64-3.8/ryml/tests/parse_bm.py -> build/bdist.linux-x86_64/wheel/ryml/tests
  copying build/lib.linux-x86_64-3.8/ryml/version.py -> build/bdist.linux-x86_64/wheel/ryml
  copying build/lib.linux-x86_64-3.8/ryml/ryml.py -> build/bdist.linux-x86_64/wheel/ryml
  running install_egg_info
  Copying api/python/rapidyaml.egg-info to build/bdist.linux-x86_64/wheel/rapidyaml-0.1.0.post60-py3.8.egg-info
  running install_scripts
  adding license file "LICENSE.txt" (matched pattern "LICEN[CS]E*")
  creating build/bdist.linux-x86_64/wheel/rapidyaml-0.1.0.post60.dist-info/WHEEL
  creating '/tmp/pip-wheel-g5z9ego2/tmprc1rdj1a/rapidyaml-0.1.0.post60-cp38-cp38-linux_x86_64.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'ryml/__init__.py'
  adding 'ryml/_ryml.so'
  adding 'ryml/ryml.py'
  adding 'ryml/version.py'
  adding 'ryml/tests/parse.py'
  adding 'ryml/tests/parse_bm.py'
  adding 'rapidyaml-0.1.0.post60.dist-info/LICENSE.txt'
  adding 'rapidyaml-0.1.0.post60.dist-info/METADATA'
  adding 'rapidyaml-0.1.0.post60.dist-info/WHEEL'
  adding 'rapidyaml-0.1.0.post60.dist-info/top_level.txt'
  adding 'rapidyaml-0.1.0.post60.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for rapidyaml (PEP 517) ... done
  Created wheel for rapidyaml: filename=rapidyaml-0.1.0.post60-cp38-cp38-linux_x86_64.whl size=135970 sha256=a9485feb753fb91c3e302be30d2d8c939049bbdd652e3bb467d2813313e0006c
  Stored in directory: /home/vagrant/.cache/pip/wheels/25/34/bf/bbaba06917e69bbc42d427c48aa5fce90a899a1aa590026329
Successfully built rapidyaml
Installing collected packages: rapidyaml
  Created temporary directory: /tmp/pip-unpacked-wheel-a9bfi8mj

Successfully installed rapidyaml-0.1.0.post60
```

**Comment by biojppm** [comment] 2021-09-27 23:32
@mkurc-ant are you able to reproduce the problem with pyenv instead of virtualenv?

**Comment by mkurc-ant** [comment] 2021-09-28 07:16
@biojppm I haven't checked that. I'll do it once I have some spare time.

**Comment by biojppm** [comment] 2021-09-28 13:39
@mkurc-ant quick note: in the meantime, version 0.2.2 came out, so when you do the check, please ensure to use the original 0.1.0.post60 package as per `pip install rapidyaml==0.1.0.post60`.

**Comment by biojppm** [comment] 2021-11-08 15:03
Closing now. Feel free to reopen.

**Closed by biojppm** 2021-11-08 15:03 UTC
